### ISSUE TITLE
[carrier-integration] Nationex 

### ISSUE THREAD

**Issue by minchaminder** [karrioapi/karrio-dashboard#138]
**Is your feature request related to a problem? Please describe.**
Request for new carrier support (Nationex Canada)

https://www.nationex.com/en/

**Comment by DanH91** [comment]
Hey @minchaminder,
Thank you, will add Nationex to the roadmap.

For carrier integrations, these are things that can help roll them out quickly:

- Share any link to the actual API documentation
- If they don't allow a simple registration to use their API, please let's chat privately to share any test credentials you have.
