### ISSUE TITLE
Cancel shipment error

### ISSUE THREAD

**Issue by rgdcastro** [karrioapi/karrio-dashboard#190]
**Describe the bug**
Whenever you try to cancel a shipment, it returns a status 400 error.

**To Reproduce**
1. Go to Shipments
2. Click on Shipments Menu
3. Click on 'Cancel Shipment'

**Expected behavior**
The shipment would be canceled and label be voided.

**Screenshots**
![image](https://user-images.githubusercontent.com/36554808/163485654-c20622cf-5e40-47e5-a6cb-71e77bdbe699.png)
![image](https://user-images.githubusercontent.com/36554808/163486477-48ff994f-e49a-4265-bdee-369ffab9b1b1.png)
![image](https://user-images.githubusercontent.com/36554808/163486750-84ffdb59-a238-4c0a-a998-611b00aa371c.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 100.0.4896.88

**Comment by danh91** [comment]
Hi @rgdcastro,

I appreciate the detailed issue. I will try to reproduce it. 
It looks like an issue on the server-side.
