### ISSUE TITLE
Dashboard doesn't load -> "Failed to fetch API data from (http://localhost:5002)"}, 

### ISSUE THREAD

**Issue by ray0711** [karrioapi/karrio-dashboard#226]
**Describe the bug**
after the login the dashboard shows an error: Failed to load intial data...
log shows the following error
`karrio.dashboard  | {"level":50,"time":1676405017300,"env":"production","msg":"Failed to fetch API data from (http://localhost:5002)"}`

**To Reproduce**

1. follow: https://github.com/karrioapi/karrio
```
git clone --depth 1 https://github.com/karrioapi/karrio
cd karrio/docker
docker compose up
```
2. open localhost:3000 in the browser
3. login

**Expected behavior**
karrio-dashboard loads without error

**Additional context**
I believe the commit below wrongly introduces requests to the external api (`KARRIO_PUBLIC_URL=localhost:5002`) instead of using the docker-internal endpoint `api:5002`

https://github.com/karrioapi/karrio-dashboard/commit/c85c1f7c58587bf1ad49f01be2cba81dc6d3df1d#diff-8c678336fa1cb4a656e7fb03ef26cd9e240dad3cd3aa7de7f08334fa500d8e86L78

When using a productive setup with DNS names the issue is unlikely to be visible but it breaks a local test setup.

**Comment by danh91** [comment]
Hi @ray0711,

Thank you for filing the issue. 
You are absolutely right about the faulty commit too.
