### ISSUE TITLE
Use "Your Packaging" as default dimension preset

### ISSUE THREAD

**Issue by MarcoWel** [karrioapi/karrio-dashboard#235]
Currently, "Medium Box" is selected by default on a fresh karrio installation. This can lead to exclusion of certain services during rate suggestion (e.g. UPS Standard).

Therefore, "Your Packaging" should be the default dimension preset.

**Comment by danh91** [comment]
I agree. We really want onboarding to be smooth.
So a default packaging that makes sure all services appear for all carriers is more suitable.
