### ISSUE TITLE
Add "Reference" column to shipment overview / Making lists customizable

### ISSUE THREAD

**Issue by MarcoWel** [karrioapi/karrio-dashboard#236]
Shipment reference is usually filled with important information such as the order number. Currently, karrio dashboard does not show this in the overview. It would be an important addition.

Ultimatively, it should be possible to customize the list views (show/hide/resort columns). There should be a selection of data available to show and sort-by (like destination country/address/name, shipping duration, expected time of delivery, ...)

![image](https://user-images.githubusercontent.com/80592577/219882181-9301bc75-bcaa-44ff-81bb-e084e783d07f.png)

Interestingly, the overview can already be filtered by shipment reference:

![image](https://user-images.githubusercontent.com/80592577/219882230-3b1d30d6-3d3a-41f8-a43c-4ca408538ec7.png)

**Comment by danh91** [comment]
I agree that reference is quite an important field. 
Especially when someone is trying to retrieve a shipment
